# train_gpt.py — La Pulga (lapulga-llm)
# Auto-generated by scripts/build_submission.py — DO NOT EDIT BY HAND
# OpenAI Parameter-Golf submission format: single standalone file

# ── Imports ─────────────────────────────────────────────────────────────
from dataclasses import dataclass
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor
from typing import Optional
import glob
from pathlib import Path
from typing import Generator, Tuple
import numpy as np
import sentencepiece as spm
import io
import zlib
import math
import copy
import os
import time
from torch.backends.cuda import enable_cudnn_sdp, enable_flash_sdp, enable_math_sdp, enable_mem_efficient_sdp
from safetensors.torch import save_file as safetensors_save

# ── domain.config ──────────────────────────────────────────────────────────

from dataclasses import dataclass


@dataclass(frozen=True)
class ModelConfig:
    """Configuration schema for the La Pulga Transformer architecture."""
    dim: int = 768
    physical_layers: int = 4
    repeat_count: int = 3
    n_heads: int = 12
    n_kv_heads: int = 4
    hidden_dim: int = 1280
    vocab_size: int = 1024
    norm_eps: float = 1e-5
    context_length: int = 1024
    logit_softcap: float = 30.0

    @property
    def effective_layers(self) -> int:
        """Total effective depth = physical layers × repeats (ALBERT-style sharing)."""
        return self.physical_layers * self.repeat_count


@dataclass(frozen=True)
class TrainingConfig:
    """Configuration schema for the training orchestration."""
    batch_size: int = 524288
    micro_batch_size: int = 131072
    context_length: int = 1024
    learning_rate: float = 6e-4
    epochs: int = 1
    train_tokens: int = 500_000_000
    val_tokens: int = 50_000
    checkpoint_path: str = "lapulga_weights.safetensors"
    tokenizer_path: str = "../parameter-golf/data/tokenizers/fineweb_1024_bpe.model"
    data_path: str = "../parameter-golf/data/datasets/fineweb10B_sp1024"
    scoring_metric: str = "bpb"

# ── model.transformer ──────────────────────────────────────────────────────

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor

from typing import Optional

DEVICE: torch.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


class CastedLinear(nn.Linear):
    """
    Keeps weights in FP32 for optimizer precision, casts to input dtype at matmul time.
    Under torch.autocast(bf16), the .to(x.dtype) is essentially free.
    Matches the official parameter-golf baseline pattern.
    """
    def forward(self, x: Tensor) -> Tensor:
        return F.linear(x, self.weight.to(x.dtype), self.bias.to(x.dtype) if self.bias is not None else None)


class RMSNorm(nn.Module):
    """Root Mean Square Layer Normalization (no learnable weight for compile compat)."""
    def __init__(self, eps: float | None = None):
        super().__init__()
        self.eps = eps

    def forward(self, x: Tensor) -> Tensor:
        return F.rms_norm(x, (x.size(-1),), eps=self.eps)


class Rotary(nn.Module):
    """
    Rotary Position Embeddings with pre-computed cos/sin tables.
    Tables are computed once at init for the fixed context_length,
    stored as buffers (no mutation during forward — torch.compile safe).
    """
    def __init__(self, dim: int, max_seq_len: int = 1024, base: float = 10000.0):
        super().__init__()
        inv_freq = 1.0 / (base ** (torch.arange(0, dim, 2, dtype=torch.float32) / dim))
        positions = torch.arange(max_seq_len, dtype=torch.float32)
        freqs = torch.outer(positions, inv_freq)
        self.register_buffer("cos_table", freqs.cos()[None, None, :, :], persistent=False)
        self.register_buffer("sin_table", freqs.sin()[None, None, :, :], persistent=False)

    def forward(self, seq_len: int, device: torch.device, dtype: torch.dtype) -> tuple[Tensor, Tensor]:
        return (
            self.cos_table[:, :, :seq_len, :].to(dtype=dtype),
            self.sin_table[:, :, :seq_len, :].to(dtype=dtype),
        )


def apply_rotary_emb(x: Tensor, cos: Tensor, sin: Tensor) -> Tensor:
    """Applies rotary embeddings using the half-rotation formula."""
    half = x.size(-1) // 2
    x1, x2 = x[..., :half], x[..., half:]
    return torch.cat((x1 * cos + x2 * sin, x1 * (-sin) + x2 * cos), dim=-1)


class Attention(nn.Module):
    """
    Grouped-Query Attention with RoPE, QK-norm, and learnable q_gain.
    Uses F.scaled_dot_product_attention for Flash Attention on CUDA.
    """
    def __init__(self, config: ModelConfig):
        super().__init__()
        self.n_heads: int = config.n_heads
        self.n_kv_heads: int = config.n_kv_heads
        self.head_dim: int = config.dim // config.n_heads
        kv_dim: int = self.n_kv_heads * self.head_dim

        self.wq = CastedLinear(config.dim, config.dim, bias=False)
        self.wk = CastedLinear(config.dim, kv_dim, bias=False)
        self.wv = CastedLinear(config.dim, kv_dim, bias=False)
        self.wo = CastedLinear(config.dim, config.dim, bias=False)
        self.wo._zero_init = True

        self.q_gain = nn.Parameter(torch.full((config.n_heads,), 1.0, dtype=torch.float32))
        self.rotary = Rotary(self.head_dim)

    def forward(self, input_tensor: Tensor) -> Tensor:
        batch_size, seq_length, _ = input_tensor.shape

        q = self.wq(input_tensor).view(batch_size, seq_length, self.n_heads, self.head_dim).transpose(1, 2)
        k = self.wk(input_tensor).view(batch_size, seq_length, self.n_kv_heads, self.head_dim).transpose(1, 2)
        v = self.wv(input_tensor).view(batch_size, seq_length, self.n_kv_heads, self.head_dim).transpose(1, 2)

        q = F.rms_norm(q, (q.size(-1),))
        k = F.rms_norm(k, (k.size(-1),))

        cos, sin = self.rotary(seq_length, input_tensor.device, q.dtype)
        q = apply_rotary_emb(q, cos, sin)
        k = apply_rotary_emb(k, cos, sin)

        q = q * self.q_gain.to(dtype=q.dtype)[None, :, None, None]

        try:
            output = F.scaled_dot_product_attention(
                q, k, v,
                attn_mask=None,
                is_causal=True,
                enable_gqa=(self.n_kv_heads != self.n_heads),
            )
        except TypeError:
            if self.n_kv_heads != self.n_heads:
                repeat_factor = self.n_heads // self.n_kv_heads
                k = k.repeat_interleave(repeat_factor, dim=1)
                v = v.repeat_interleave(repeat_factor, dim=1)
            output = F.scaled_dot_product_attention(
                q, k, v,
                attn_mask=None,
                is_causal=True,
            )
        output = output.transpose(1, 2).contiguous().reshape(batch_size, seq_length, -1)
        return self.wo(output)


class MLP(nn.Module):
    """
    ReLU^2 Feed-Forward block (official Parameter-Golf baseline).
    Uses 2 weight matrices vs SwiGLU's 3, saving ~33% MLP parameters.
    """
    def __init__(self, config: ModelConfig):
        super().__init__()
        self.fc = CastedLinear(config.dim, config.hidden_dim, bias=False)
        self.proj = CastedLinear(config.hidden_dim, config.dim, bias=False)
        self.proj._zero_init = True

    def forward(self, input_tensor: Tensor) -> Tensor:
        hidden = torch.relu(self.fc(input_tensor))
        return self.proj(hidden.square())


class TransformerBlock(nn.Module):
    """
    Single Transformer layer with learnable attn/mlp scales and residual mixing.
    resid_mix blends the current residual with the original embedding at each pass,
    which is especially useful under ALBERT-style repetition for gradient flow.
    """
    def __init__(self, config: ModelConfig):
        super().__init__()
        self.attention = Attention(config)
        self.feed_forward = MLP(config)
        self.attention_norm = RMSNorm()
        self.ffn_norm = RMSNorm()
        self.attn_scale = nn.Parameter(torch.ones(config.dim, dtype=torch.float32))
        self.mlp_scale = nn.Parameter(torch.ones(config.dim, dtype=torch.float32))
        self.resid_mix = nn.Parameter(
            torch.stack((torch.ones(config.dim), torch.zeros(config.dim))).float()
        )

    def forward(self, input_tensor: Tensor, x0: Tensor) -> Tensor:
        mix = self.resid_mix.to(dtype=input_tensor.dtype)
        x = mix[0][None, None, :] * input_tensor + mix[1][None, None, :] * x0

        attn_out = self.attention(self.attention_norm(x))
        x = x + self.attn_scale.to(dtype=x.dtype)[None, None, :] * attn_out
        x = x + self.mlp_scale.to(dtype=x.dtype)[None, None, :] * self.feed_forward(self.ffn_norm(x))
        return x


class LanguageModel(nn.Module):
    """
    La Pulga — Fat ALBERT variant for H100.

    ALBERT-style Cross-Layer Sharing: 4 physical blocks repeated 3× = 12 effective layers.
    The ALBERT loop is UNROLLED into self.full_sequence for torch.compile compatibility.
    Modules are repeated references (shared weights), so param count stays the same.
    """
    def __init__(self, config: ModelConfig):
        super().__init__()
        self.config = config
        self.vocab_size: int = config.vocab_size
        self.logit_softcap: float = config.logit_softcap

        self.tok_embeddings = nn.Embedding(config.vocab_size, config.dim)

        # U-Net skip connections indexed over effective (virtual) layer depth
        num_encoder: int = config.effective_layers // 2
        num_decoder: int = config.effective_layers - num_encoder
        self.num_skip_weights: int = min(num_encoder, num_decoder)
        self.skip_weights = nn.Parameter(
            torch.ones(self.num_skip_weights, config.dim, dtype=torch.float32)
        )

        # Physical layers — only these hold unique parameters
        self.layers = nn.ModuleList([TransformerBlock(config) for _ in range(config.physical_layers)])

        # UNROLLED sequence: repeated references to the physical layers.
        # torch.compile sees 12 linear calls, NOT a Python loop.
        # Weights are shared — self.full_sequence[0] IS self.layers[0].
        self.full_sequence = nn.ModuleList()
        for _ in range(config.repeat_count):
            for layer in self.layers:
                self.full_sequence.append(layer)

        self.norm = RMSNorm()

        self._init_weights()

    def _init_weights(self) -> None:
        nn.init.normal_(self.tok_embeddings.weight, mean=0.0, std=0.02)
        for module in self.modules():
            if isinstance(module, nn.Linear) and getattr(module, "_zero_init", False):
                nn.init.zeros_(module.weight)

    def forward(self, input_ids: Tensor, target_ids: Optional[Tensor] = None) -> Tensor:
        x = self.tok_embeddings(input_ids)
        x = F.rms_norm(x, (x.size(-1),))
        x0 = x
        skips: list[Tensor] = []

        num_encoder: int = self.config.effective_layers // 2
        decoder_step: int = 0

        # Unrolled linear sequence — clean path, no branches
        for virtual_idx, block in enumerate(self.full_sequence):
            if virtual_idx < num_encoder:
                x = block(x, x0)
                skips.append(x)
            else:
                if skips:
                    sw = self.skip_weights[decoder_step].to(dtype=x.dtype)[None, None, :]
                    x = x + sw * skips.pop()
                x = block(x, x0)
                decoder_step += 1

        x = self.norm(x)

        # Weight Tying: reuse tok_embeddings.weight as the output head
        logits = F.linear(x, self.tok_embeddings.weight.to(x.dtype))
        logits = self.logit_softcap * torch.tanh(logits / self.logit_softcap)

        if target_ids is not None:
            return F.cross_entropy(
                logits.float().reshape(-1, self.vocab_size),
                target_ids.reshape(-1),
                reduction="mean",
            )
        return logits

    @property
    def device(self) -> torch.device:
        return self.tok_embeddings.weight.device

# ── data.shard_loader ──────────────────────────────────────────────────────

import glob
from pathlib import Path
from typing import Generator, Tuple

import numpy as np
import torch
from torch import Tensor

SHARD_MAGIC: int = 20240520
SHARD_VERSION: int = 1


def load_data_shard(file: Path) -> Tensor:
    """
    Reads a single FineWeb binary shard.

    Format: 256 × little-endian int32 header, followed by uint16 tokens.
    Header[0] = magic (20240520), Header[1] = version (1), Header[2] = num_tokens.
    """
    header_bytes: int = 256 * np.dtype("<i4").itemsize
    token_bytes: int = np.dtype("<u2").itemsize

    header = np.fromfile(file, dtype="<i4", count=256)
    if header.size != 256 or int(header[0]) != SHARD_MAGIC or int(header[1]) != SHARD_VERSION:
        raise ValueError(f"Unexpected shard header for {file}")

    num_tokens: int = int(header[2])
    expected_size: int = header_bytes + num_tokens * token_bytes
    if file.stat().st_size != expected_size:
        raise ValueError(f"Shard size mismatch for {file}: expected {expected_size} bytes")

    tokens_np = np.fromfile(file, dtype="<u2", count=num_tokens, offset=header_bytes)
    if tokens_np.size != num_tokens:
        raise ValueError(f"Short read for {file}")

    return torch.from_numpy(tokens_np.astype(np.uint16, copy=False))


class TokenStream:
    """
    Reads shards sequentially and wraps around forever.
    Deterministic streaming — no sampling, no workers.
    """
    def __init__(self, pattern: str):
        self.files = [Path(p) for p in sorted(glob.glob(pattern))]
        if not self.files:
            raise FileNotFoundError(f"No files found for pattern: {pattern}")
        self.file_idx: int = 0
        self.tokens: Tensor = load_data_shard(self.files[0])
        self.pos: int = 0

    def _advance_file(self) -> None:
        """Move to the next shard, wrapping around to the first when exhausted."""
        self.file_idx = (self.file_idx + 1) % len(self.files)
        self.tokens = load_data_shard(self.files[self.file_idx])
        self.pos = 0

    def take(self, n: int) -> Tensor:
        """Consume exactly n tokens from the stream, crossing shard boundaries."""
        chunks: list[Tensor] = []
        remaining: int = n
        while remaining > 0:
            avail: int = self.tokens.numel() - self.pos
            if avail <= 0:
                self._advance_file()
                continue
            k: int = min(remaining, avail)
            chunks.append(self.tokens[self.pos : self.pos + k])
            self.pos += k
            remaining -= k
        return chunks[0] if len(chunks) == 1 else torch.cat(chunks)


def load_validation_tokens(pattern: str, seq_len: int) -> Tensor:
    """
    Loads and concatenates all validation shard files into a single token tensor.
    Trims to a multiple of seq_len + 1 for clean (x, y) batch slicing.
    """
    files = [Path(p) for p in sorted(glob.glob(pattern))]
    if not files:
        raise FileNotFoundError(f"No files found for pattern: {pattern}")
    tokens: Tensor = torch.cat([load_data_shard(f) for f in files]).contiguous()
    usable: int = ((tokens.numel() - 1) // seq_len) * seq_len
    if usable <= 0:
        raise ValueError(f"Validation split is too short for seq_len={seq_len}")
    return tokens[: usable + 1]


def get_fineweb_batches(
    tokens: Tensor,
    seq_len: int,
    device: torch.device = torch.device("cpu"),
) -> Generator[Tuple[Tensor, Tensor], None, None]:
    """
    Yields (inputs, targets) from a flat validation token tensor.
    Each batch is a single sequence of length seq_len.
    """
    total_seqs: int = (tokens.numel() - 1) // seq_len
    for i in range(total_seqs):
        start: int = i * seq_len
        local = tokens[start : start + seq_len + 1].to(dtype=torch.int64)
        x = local[:-1].unsqueeze(0).to(device, non_blocking=True)
        y = local[1:].unsqueeze(0).to(device, non_blocking=True)
        yield x, y

# ── data.tokenizer ─────────────────────────────────────────────────────────

import numpy as np
import torch
from torch import Tensor
import sentencepiece as spm


def load_sentencepiece(path: str) -> spm.SentencePieceProcessor:
    """Loads a SentencePiece .model file from disk."""
    sp = spm.SentencePieceProcessor()
    sp.Load(path)
    return sp


def build_bpb_lookup_tables(
    sp: spm.SentencePieceProcessor,
    vocab_size: int,
    device: torch.device,
) -> tuple[Tensor, Tensor, Tensor]:
    """
    Builds three lookup tables for BPB (Bits Per Byte) calculation.

    Why BPB instead of perplexity?
    BPB is tokenizer-agnostic: it measures compression in bits per UTF-8 byte,
    so models with different tokenizers can be compared fairly. This is the
    official scoring metric for the Parameter-Golf challenge.

    Returns:
        base_bytes_lut: UTF-8 byte count per token (int16)
        has_leading_space_lut: whether the token starts with the SentencePiece
            space marker (U+2581 "▁") (bool)
        is_boundary_token_lut: whether the token is a control/unknown/unused
            marker that contributes zero bytes (bool)
    """
    sp_vocab_size: int = int(sp.vocab_size())
    table_size: int = max(sp_vocab_size, vocab_size)

    base_bytes_np = np.zeros((table_size,), dtype=np.int16)
    has_leading_space_np = np.zeros((table_size,), dtype=np.bool_)
    is_boundary_token_np = np.ones((table_size,), dtype=np.bool_)

    for token_id in range(sp_vocab_size):
        if sp.is_control(token_id) or sp.is_unknown(token_id) or sp.is_unused(token_id):
            continue
        is_boundary_token_np[token_id] = False
        if sp.is_byte(token_id):
            base_bytes_np[token_id] = 1
            continue
        piece: str = sp.id_to_piece(token_id)
        if piece.startswith("▁"):
            has_leading_space_np[token_id] = True
            piece = piece[1:]
        base_bytes_np[token_id] = len(piece.encode("utf-8"))

    return (
        torch.tensor(base_bytes_np, dtype=torch.int16, device=device),
        torch.tensor(has_leading_space_np, dtype=torch.bool, device=device),
        torch.tensor(is_boundary_token_np, dtype=torch.bool, device=device),
    )

# ── utils.quantize ─────────────────────────────────────────────────────────

import io
import zlib
from pathlib import Path

import torch
from torch import Tensor

INT8_KEEP_FLOAT_MAX_NUMEL: int = 16_384
INT8_KEEP_FLOAT_STORE_DTYPE: torch.dtype = torch.float16
INT8_PER_ROW_SCALE_DTYPE: torch.dtype = torch.float16
INT8_CLIP_PERCENTILE: float = 99.99984
INT8_CLIP_Q: float = INT8_CLIP_PERCENTILE / 100.0

CONTROL_TENSOR_PATTERNS: tuple[str, ...] = (
    "attn_scale", "mlp_scale", "resid_mix", "q_gain", "skip_weight",
)


def _tensor_nbytes(t: Tensor) -> int:
    """Returns the byte size of a tensor's data."""
    return int(t.numel()) * int(t.element_size())


def _keep_float_tensor(name: str, t: Tensor, passthrough_orig_dtypes: dict[str, str]) -> Tensor:
    """Decides how to store small/control tensors that skip int8 quantization."""
    if any(pattern in name for pattern in CONTROL_TENSOR_PATTERNS):
        return t.float().contiguous()
    if t.dtype in {torch.float32, torch.bfloat16}:
        passthrough_orig_dtypes[name] = str(t.dtype).removeprefix("torch.")
        return t.to(dtype=INT8_KEEP_FLOAT_STORE_DTYPE).contiguous()
    return t


def quantize_float_tensor(t: Tensor) -> tuple[Tensor, Tensor]:
    """
    Quantizes a single float tensor to int8.
    - 2D tensors: per-row quantization (one scale per output channel)
    - 1D/scalar tensors: per-tensor quantization
    """
    t32 = t.float()
    if t32.ndim == 2:
        clip_abs = (
            torch.quantile(t32.abs(), INT8_CLIP_Q, dim=1)
            if t32.numel()
            else torch.empty((t32.shape[0],), dtype=torch.float32)
        )
        clipped = torch.maximum(torch.minimum(t32, clip_abs[:, None]), -clip_abs[:, None])
        scale = (clip_abs / 127.0).clamp_min(1.0 / 127.0)
        q = torch.clamp(torch.round(clipped / scale[:, None]), -127, 127).to(torch.int8).contiguous()
        return q, scale.to(dtype=INT8_PER_ROW_SCALE_DTYPE).contiguous()

    # Vectors / scalars: single scale for the whole tensor
    clip_abs = float(torch.quantile(t32.abs().flatten(), INT8_CLIP_Q).item()) if t32.numel() else 0.0
    scale = torch.tensor(clip_abs / 127.0 if clip_abs > 0 else 1.0, dtype=torch.float32)
    q = torch.clamp(torch.round(torch.clamp(t32, -clip_abs, clip_abs) / scale), -127, 127).to(torch.int8).contiguous()
    return q, scale


def quantize_state_dict_int8(state_dict: dict[str, Tensor]) -> tuple[dict, dict]:
    """
    Quantizes a full model state_dict to int8.

    Returns:
        (quantized_obj, stats) — the serializable quantized object and size statistics
    """
    quantized: dict[str, Tensor] = {}
    scales: dict[str, Tensor] = {}
    dtypes: dict[str, str] = {}
    passthrough: dict[str, Tensor] = {}
    passthrough_orig_dtypes: dict[str, str] = {}
    qmeta: dict[str, dict[str, object]] = {}
    stats: dict[str, int] = {
        "param_count": 0,
        "num_tensors": 0,
        "baseline_tensor_bytes": 0,
        "int8_payload_bytes": 0,
    }

    for name, tensor in state_dict.items():
        t = tensor.detach().to("cpu").contiguous()
        stats["param_count"] += int(t.numel())
        stats["num_tensors"] += 1
        stats["baseline_tensor_bytes"] += _tensor_nbytes(t)

        if not t.is_floating_point():
            passthrough[name] = t
            stats["int8_payload_bytes"] += _tensor_nbytes(t)
            continue

        # Small tensors are cheap enough to keep without int8
        if t.numel() <= INT8_KEEP_FLOAT_MAX_NUMEL:
            kept = _keep_float_tensor(name, t, passthrough_orig_dtypes)
            passthrough[name] = kept
            stats["int8_payload_bytes"] += _tensor_nbytes(kept)
            continue

        q, s = quantize_float_tensor(t)
        if s.ndim > 0:
            qmeta[name] = {"scheme": "per_row", "axis": 0}
        quantized[name] = q
        scales[name] = s
        dtypes[name] = str(t.dtype).removeprefix("torch.")
        stats["int8_payload_bytes"] += _tensor_nbytes(q) + _tensor_nbytes(s)

    obj: dict[str, object] = {
        "__quant_format__": "int8_clean_per_row_v1",
        "quantized": quantized,
        "scales": scales,
        "dtypes": dtypes,
        "passthrough": passthrough,
    }
    if qmeta:
        obj["qmeta"] = qmeta
    if passthrough_orig_dtypes:
        obj["passthrough_orig_dtypes"] = passthrough_orig_dtypes
    return obj, stats


def dequantize_state_dict_int8(obj: dict[str, object]) -> dict[str, Tensor]:
    """Dequantizes an int8 quantized object back to float tensors."""
    out: dict[str, Tensor] = {}
    qmeta = obj.get("qmeta", {})
    passthrough_orig_dtypes = obj.get("passthrough_orig_dtypes", {})

    for name, q in obj["quantized"].items():
        dtype = getattr(torch, obj["dtypes"][name])
        s = obj["scales"][name]
        if qmeta.get(name, {}).get("scheme") == "per_row" or s.ndim > 0:
            s = s.to(dtype=torch.float32)
            out[name] = (q.float() * s.view(q.shape[0], *([1] * (q.ndim - 1)))).to(dtype=dtype).contiguous()
        else:
            scale = float(s.item())
            out[name] = (q.float() * scale).to(dtype=dtype).contiguous()

    for name, t in obj["passthrough"].items():
        out_t = t.detach().to("cpu").contiguous()
        orig_dtype = passthrough_orig_dtypes.get(name)
        if isinstance(orig_dtype, str):
            out_t = out_t.to(dtype=getattr(torch, orig_dtype)).contiguous()
        out[name] = out_t

    return out


def compute_artifact_size(state_dict: dict[str, Tensor], code_path: Path) -> tuple[int, int, int]:
    """
    Computes the total submission artifact size: code bytes + zlib(int8 model).

    Returns:
        (total_bytes, code_bytes, model_bytes)
    """
    code_bytes: int = len(code_path.read_bytes()) if code_path.exists() else 0

    obj, _stats = quantize_state_dict_int8(state_dict)
    buf = io.BytesIO()
    torch.save(obj, buf)
    raw_bytes = buf.getvalue()
    compressed = zlib.compress(raw_bytes, level=9)
    model_bytes: int = len(compressed)

    total_bytes: int = code_bytes + model_bytes
    return total_bytes, code_bytes, model_bytes

# ── utils.evaluate_bpb ─────────────────────────────────────────────────────

import math
import torch
import torch.nn.functional as F
from torch import Tensor


@torch.no_grad()
def compute_bpb(
    model: torch.nn.Module,
    val_tokens: Tensor,
    seq_len: int,
    base_bytes_lut: Tensor,
    has_leading_space_lut: Tensor,
    is_boundary_token_lut: Tensor,
    device: torch.device,
) -> tuple[float, float]:
    """
    Computes both validation loss and BPB on a token tensor.

    The BPB formula:
        bits_per_token = val_loss / ln(2)
        tokens_per_byte = total_tokens / total_utf8_bytes
        bpb = bits_per_token * tokens_per_byte

    Returns:
        (val_loss, val_bpb) — loss in nats and BPB score
    """
    model.eval()

    total_seqs: int = (val_tokens.numel() - 1) // seq_len
    val_loss_sum = torch.zeros((), device=device, dtype=torch.float64)
    val_token_count = torch.zeros((), device=device, dtype=torch.float64)
    val_byte_count = torch.zeros((), device=device, dtype=torch.float64)

    for seq_idx in range(total_seqs):
        start: int = seq_idx * seq_len
        local = val_tokens[start : start + seq_len + 1].to(device=device, dtype=torch.int64)
        x = local[:-1].unsqueeze(0)
        y = local[1:].unsqueeze(0)

        with torch.amp.autocast(device_type=device.type, enabled=(device.type == "cuda")):
            loss = model(x, y).detach()

        batch_token_count: float = float(y.numel())
        val_loss_sum += loss.to(torch.float64) * batch_token_count
        val_token_count += batch_token_count

        # Count UTF-8 bytes using the SentencePiece lookup tables
        prev_ids = x.reshape(-1)
        tgt_ids = y.reshape(-1)
        token_bytes = base_bytes_lut[tgt_ids].to(dtype=torch.int16)
        # Leading space contributes +1 byte when the previous token is not a boundary
        token_bytes += (has_leading_space_lut[tgt_ids] & ~is_boundary_token_lut[prev_ids]).to(dtype=torch.int16)
        val_byte_count += token_bytes.to(torch.float64).sum()

    val_loss: float = (val_loss_sum / val_token_count).item()
    bits_per_token: float = val_loss / math.log(2.0)
    tokens_per_byte: float = val_token_count.item() / val_byte_count.item()
    val_bpb: float = bits_per_token * tokens_per_byte

    return val_loss, val_bpb

# ── utils.generate ─────────────────────────────────────────────────────────

import torch
import torch.nn.functional as F
import sentencepiece as spm


@torch.compiler.disable
@torch.no_grad()
def generate_text(
    model: LanguageModel,
    sp: spm.SentencePieceProcessor,
    prompt: str,
    max_tokens: int = 50,
    temperature: float = 0.8,
    top_k: int = 50,
    repetition_penalty: float = 1.2,
) -> str:
    """
    Takes a string prompt, tokenizes it, and iteratively predicts the next tokens.
    Iterates autoregressively by appending the newly generated token back to the context.
    """
    model.eval()
    device = model.device
    ctx_len: int = model.config.context_length

    input_ids: list[int] = sp.encode(prompt)
    print(f"Thinking with temperature {temperature}...")

    for _ in range(max_tokens):
        # Truncate to context window
        context = input_ids[-ctx_len:]
        input_tensor = torch.tensor([context], dtype=torch.long, device=device)

        logits = model(input_tensor)
        next_token_logits = logits[0, -1, :].clone()

        # Repetition penalty (HuggingFace standard)
        if repetition_penalty != 1.0:
            seen = set(input_ids)
            for token_id in seen:
                if next_token_logits[token_id] > 0:
                    next_token_logits[token_id] /= repetition_penalty
                else:
                    next_token_logits[token_id] *= repetition_penalty

        if temperature > 0:
            scaled_logits = next_token_logits / temperature

            # Top-k filtering
            if top_k > 0 and top_k < scaled_logits.size(0):
                top_k_vals, top_k_idx = torch.topk(scaled_logits, top_k)
                filtered = torch.full_like(scaled_logits, float('-inf'))
                filtered.scatter_(0, top_k_idx, top_k_vals)
                scaled_logits = filtered

            probs = F.softmax(scaled_logits, dim=-1)
            next_token_id: int = torch.multinomial(probs, num_samples=1).item()
        else:
            next_token_id: int = torch.argmax(next_token_logits).item()

        input_ids.append(next_token_id)

    generated_text: str = sp.decode(input_ids)
    return generated_text

# ── training.loop ──────────────────────────────────────────────────────────

import copy
import io
import math
import os
import time
import zlib

import torch
import torch.nn.functional as F
from torch.backends.cuda import enable_cudnn_sdp, enable_flash_sdp, enable_math_sdp, enable_mem_efficient_sdp
from safetensors.torch import save_file as safetensors_save

DEFAULT_COMPILE_WARMUP_STEPS: int = 8


def _next_chunk(
    all_tokens: torch.Tensor,
    token_cursor: int,
    need: int,
    total_available: int,
) -> tuple[torch.Tensor, int]:
    if token_cursor + need > total_available:
        token_cursor = 0
    chunk = all_tokens[token_cursor : token_cursor + need]
    return chunk, token_cursor + (need - 1)


def execute_training(model: LanguageModel, train_config: TrainingConfig) -> None:
    """
    Executes the main optimization loop on FineWeb shards.
    All training data is pre-loaded into RAM to eliminate I/O bottlenecks.
    Uses CastedLinear (FP32 weights) and torch.compile(max-autotune).
    """
    dev_mode: bool = os.environ.get("DEV_MODE", "0") == "1"

    # ------------------------------------------------------------
    # CUDA Knobs — match official baseline
    # ------------------------------------------------------------
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    enable_cudnn_sdp(False)
    enable_flash_sdp(True)
    enable_mem_efficient_sdp(False)
    enable_math_sdp(False)

    # ------------------------------------------------------------
    # Model setup: bf16 body, FP32 CastedLinear weights + scalars
    # Matches official parameter-golf pattern for optimizer precision.
    # ------------------------------------------------------------
    model.to(DEVICE)
    model.bfloat16()
    # Restore CastedLinear weights to FP32 (cast to bf16 happens at matmul time)
    for module in model.modules():
        if isinstance(module, CastedLinear):
            module.float()
    # Restore small/control params to FP32 for optimizer stability
    with torch.no_grad():
        for param in model.parameters():
            if param.ndim < 2 and param.dtype != torch.float32:
                param.data = param.data.float()

    model.train()

    compile_enabled: bool = os.environ.get("COMPILE_MODEL", "1") == "1" and DEVICE.type == "cuda"
    compile_mode: str = os.environ.get("TORCH_COMPILE_MODE", "default")
    if compile_enabled:
        print(f"Compiling model (torch.compile, mode={compile_mode})...")
        compiled_model = torch.compile(model, mode=compile_mode)
    else:
        print("torch.compile disabled for this run")
        compiled_model = model

    # ------------------------------------------------------------
    # Optimizer — fused AdamW
    # ------------------------------------------------------------
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=train_config.learning_rate,
        fused=True,
    )

    seq_len: int = train_config.context_length
    batch_tokens: int = train_config.batch_size
    micro_tokens: int = train_config.micro_batch_size
    accum_steps: int = max(1, batch_tokens // micro_tokens)
    grad_scale: float = 1.0 / accum_steps

    # ------------------------------------------------------------
    # Pre-load ALL training data into pinned RAM
    # ------------------------------------------------------------
    shard_pattern: str = os.path.join(train_config.data_path, "fineweb_train_*.bin")
    all_tokens: torch.Tensor = preload_train_tokens(shard_pattern)
    token_cursor: int = 0
    total_available: int = all_tokens.numel()

    # ------------------------------------------------------------
    # Training schedule
    # ------------------------------------------------------------
    steps_per_epoch: int = max(1, train_config.train_tokens // batch_tokens)
    total_steps: int = steps_per_epoch * train_config.epochs

    if dev_mode:
        total_steps = min(total_steps, 100)
        steps_per_epoch = min(steps_per_epoch, 100)
        print("*** DEV_MODE: capped at 100 steps ***")

    log_interval: int = 10 if dev_mode else 50
    lr_warmup_steps: int = max(1, int(total_steps * 0.05))

    def lr_lambda(step: int) -> float:
        if step < lr_warmup_steps:
            return step / lr_warmup_steps
        progress = (step - lr_warmup_steps) / max(1, total_steps - lr_warmup_steps)
        return 0.5 * (1.0 + math.cos(math.pi * progress))

    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)

    # ------------------------------------------------------------
    # Compiler warmup: run N throwaway steps, then reset state
    # ------------------------------------------------------------
    warmup_steps_count = 0 if dev_mode or not compile_enabled else int(os.environ.get("COMPILE_WARMUP_STEPS", str(DEFAULT_COMPILE_WARMUP_STEPS)))
    if warmup_steps_count > 0:
        print(f"Running {warmup_steps_count} compiler warmup steps (state will be reset)...")
        initial_model_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
        initial_optimizer_state = copy.deepcopy(optimizer.state_dict())

        for _ in range(warmup_steps_count):
            optimizer.zero_grad(set_to_none=True)
            for _ in range(accum_steps):
                need = micro_tokens + 1
                chunk, token_cursor = _next_chunk(all_tokens, token_cursor, need, total_available)
                x = chunk[:-1].reshape(-1, seq_len).to(device=DEVICE, dtype=torch.int64, non_blocking=True)
                y = chunk[1:].reshape(-1, seq_len).to(device=DEVICE, dtype=torch.int64, non_blocking=True)
                with torch.autocast(device_type=DEVICE.type, dtype=torch.bfloat16):
                    loss = compiled_model(x, y)
                (loss * grad_scale).backward()
            optimizer.step()

        # Reset to true initial state — timer starts here
        model.load_state_dict(initial_model_state, strict=True)
        optimizer.load_state_dict(initial_optimizer_state)
        optimizer.zero_grad(set_to_none=True)
        token_cursor = 0
        torch.cuda.synchronize()
        print("Warmup complete. Weights reset to init. Starting real training...")

    print(f"--- Starting La Pulga Training Loop on {DEVICE} ---")
    print(f"    Batch tokens: {batch_tokens:,} | Micro tokens: {micro_tokens:,} | Accum steps: {accum_steps}")
    print(f"    Seq len: {seq_len} | Steps/epoch: {steps_per_epoch} | Total steps: {total_steps}")
    print(f"    LR: {train_config.learning_rate} | LR warmup: {lr_warmup_steps} steps | Log every {log_interval} steps")
    print(f"    torch.compile: {'enabled' if compile_enabled else 'disabled'} | mode={compile_mode}")

    # ------------------------------------------------------------
    # Main training loop
    # ------------------------------------------------------------
    torch.cuda.synchronize()
    for epoch in range(train_config.epochs):
        epoch_loss: float = 0.0

        for step in range(steps_per_epoch):
            t0: float = time.perf_counter()

            optimizer.zero_grad(set_to_none=True)
            step_loss = torch.zeros((), device=DEVICE)

            for _ in range(accum_steps):
                need = micro_tokens + 1
                chunk, token_cursor = _next_chunk(all_tokens, token_cursor, need, total_available)
                x = chunk[:-1].reshape(-1, seq_len).to(device=DEVICE, dtype=torch.int64, non_blocking=True)
                y = chunk[1:].reshape(-1, seq_len).to(device=DEVICE, dtype=torch.int64, non_blocking=True)

                with torch.autocast(device_type=DEVICE.type, dtype=torch.bfloat16):
                    loss = compiled_model(x, y)

                step_loss += loss.detach()
                (loss * grad_scale).backward()

            optimizer.step()
            scheduler.step()

            # Single GPU→CPU sync per step
            step_loss_float: float = (step_loss / accum_steps).item()
            t1: float = time.perf_counter()
            epoch_loss += step_loss_float

            if step % log_interval == 0:
                bpb_est: float = step_loss_float / math.log(2)
                lr_now: float = scheduler.get_last_lr()[0]
                print(
                    f"Epoch {epoch} | Step {step:04d}/{steps_per_epoch} | "
                    f"Loss {step_loss_float:.4f} | BPB ~{bpb_est:.4f} | "
                    f"LR {lr_now:.2e} | Time {t1-t0:.4f}s"
                )

        avg_epoch_loss: float = epoch_loss / steps_per_epoch
        print(f"--- Epoch {epoch} complete | Avg Loss: {avg_epoch_loss:.4f} ---")

    # ------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------
    orig_model = getattr(model, "_orig_mod", model)
    raw_state_dict = orig_model.state_dict()

    print("--- Saving Checkpoint (.safetensors) ---")
    cpu_state_dict = {k: v.cpu().contiguous() for k, v in raw_state_dict.items()}
    safetensors_save(cpu_state_dict, train_config.checkpoint_path)
    print(f"Checkpoint saved to {train_config.checkpoint_path}")

    print("--- Building Submission Artifact (int8 + zlib) ---")
    obj, stats = quantize_state_dict_int8(raw_state_dict)
    buf = io.BytesIO()
    torch.save(obj, buf)
    compressed = zlib.compress(buf.getvalue(), level=9)

    artifact_path: str = train_config.checkpoint_path.replace(".safetensors", "_submission.pt.zlib")
    with open(artifact_path, "wb") as f:
        f.write(compressed)

    model_bytes: int = len(compressed)
    print(f"Submission artifact saved to {artifact_path}")
    print(f"Int8+zlib size: {model_bytes:,} bytes ({model_bytes / 1_000_000:.2f} MB)")
    print(f"Params quantized: {stats['param_count']:,}")

# ── main ───────────────────────────────────────────────────────────────────

import os
import torch
from pathlib import Path


def main() -> None:
    """Main execution block."""
    # Enable TF32 on Ampere+ GPUs for faster matmuls
    torch.set_float32_matmul_precision("high")

    # 1. Domain Configs (Pure Python)
    model_config = ModelConfig()
    train_config = TrainingConfig()

    # 2. Framework Backend Setup
    model = LanguageModel(model_config).to(DEVICE)
    model.train()
    num_params: int = sum(p.numel() for p in model.parameters())
    print(f"Model Parameters: {num_params:,}")
    print(f"Device: {DEVICE}")

    # 3. Load SentencePiece tokenizer + BPB lookup tables
    sp = load_sentencepiece(train_config.tokenizer_path)
    print(f"SentencePiece tokenizer loaded: {sp.vocab_size()} tokens")
    base_bytes_lut, has_leading_space_lut, is_boundary_token_lut = build_bpb_lookup_tables(
        sp, model_config.vocab_size, DEVICE,
    )

    # 4. Load validation tokens
    val_pattern: str = os.path.join(train_config.data_path, "fineweb_val_*.bin")
    val_tokens = load_validation_tokens(val_pattern, train_config.context_length)
    print(f"Validation tokens: {val_tokens.numel():,}")

    # 5. Training (reads FineWeb shards internally via TokenStream)
    execute_training(model=model, train_config=train_config)

    # 6. BPB Evaluation (official scoring metric)
    print("\n--- Measuring BPB ---")
    val_loss, val_bpb = compute_bpb(
        model, val_tokens, train_config.context_length,
        base_bytes_lut, has_leading_space_lut, is_boundary_token_lut,
        device=DEVICE,
    )
    print(f"Validation Loss: {val_loss:.4f} | Validation BPB: {val_bpb:.4f}")

    # 7. Artifact Size Report
    print("\n--- Artifact Size ---")
    code_path = Path(__file__)
    total_bytes, code_bytes, model_bytes = compute_artifact_size(model.state_dict(), code_path)
    print(f"Code: {code_bytes:,} bytes | Model (int8+zlib): {model_bytes:,} bytes")
    print(f"Total: {total_bytes:,} / 16,000,000 bytes")
    if total_bytes < 16_000_000:
        print("PASS: Under 16MB limit")
    else:
        print("FAIL: Exceeds 16MB limit!")

    # 8. Text Generation (quick sample)
    print("\n--- Generating Text ---")
    sample: str = generate_text(model, sp, "The little dog", max_tokens=60, temperature=0.7, top_k=50, repetition_penalty=1.2)
    print("-" * 40)
    print(f"Output:\n\n{sample}")
    print("-" * 40)


if __name__ == "__main__":
    main()

