"""
Submission Flattener for lapulga-llm.

Concatenates all modular source files into a single standalone train_gpt.py
as required by the OpenAI Parameter-Golf competition rules.

Usage:
    python scripts/build_submission.py
    # Output: records/lapulga-llm/train_gpt.py
"""
import ast
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
OUTPUT_DIR = PROJECT_ROOT / "records" / "lapulga-llm"
OUTPUT_FILE = OUTPUT_DIR / "train_gpt.py"

# Source files in dependency order (dependencies first)
MODULE_FILES: list[tuple[str, Path]] = [
    ("domain.config",       PROJECT_ROOT / "src" / "domain" / "config.py"),
    ("model.transformer",   PROJECT_ROOT / "src" / "model" / "transformer.py"),
    ("data.shard_loader",   PROJECT_ROOT / "src" / "data" / "shard_loader.py"),
    ("data.tokenizer",      PROJECT_ROOT / "src" / "data" / "tokenizer.py"),
    ("utils.quantize",      PROJECT_ROOT / "src" / "utils" / "quantize.py"),
    ("utils.evaluate_bpb",  PROJECT_ROOT / "src" / "utils" / "evaluate_bpb.py"),
    ("utils.generate",      PROJECT_ROOT / "src" / "utils" / "generate.py"),
    ("training.loop",       PROJECT_ROOT / "src" / "training" / "loop.py"),
    ("main",                PROJECT_ROOT / "main.py"),
]

# Patterns that identify internal imports to strip
INTERNAL_IMPORT_PATTERNS = [
    re.compile(r"^\s*from\s+src\b.*"),
    re.compile(r"^\s*import\s+src\b.*"),
]


def is_internal_import(line: str) -> bool:
    return any(p.match(line) for p in INTERNAL_IMPORT_PATTERNS)


def extract_stdlib_imports(source: str) -> list[str]:
    """Return all top-level import lines that are NOT internal src imports."""
    imports = []
    for line in source.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if is_internal_import(line):
            continue
        if stripped.startswith("import ") or stripped.startswith("from "):
            imports.append(stripped)
    return imports


def strip_module(source: str, module_label: str) -> str:
    """
    Remove:
    - Module-level docstring (first triple-quoted string)
    - All internal src.* imports
    - 'if __name__ == "__main__":' guard (non-main files only)

    Returns cleaned body lines.
    """
    lines = source.splitlines()
    out_lines: list[str] = []
    i = 0

    # Skip leading module docstring
    # Find first non-empty, non-comment line
    while i < len(lines) and lines[i].strip() == "":
        i += 1
    if i < len(lines) and lines[i].strip().startswith('"""'):
        # Find closing triple quote
        if lines[i].strip().count('"""') >= 2 and len(lines[i].strip()) > 6:
            i += 1  # single-line docstring
        else:
            i += 1
            while i < len(lines) and '"""' not in lines[i]:
                i += 1
            i += 1  # skip closing """

    for line in lines[i:]:
        # Drop internal imports
        if is_internal_import(line):
            continue
        # Drop duplicate stdlib/third-party imports (handled by dedup pass)
        out_lines.append(line)

    # Remove trailing blank lines
    while out_lines and out_lines[-1].strip() == "":
        out_lines.pop()

    return "\n".join(out_lines)


def build() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    seen_imports: set[str] = set()
    all_imports: list[str] = []
    all_bodies: list[tuple[str, str]] = []

    for label, path in MODULE_FILES:
        if not path.exists():
            print(f"  WARNING: {path} not found, skipping", file=sys.stderr)
            continue

        source = path.read_text(encoding="utf-8")

        # Collect imports from this file
        for imp in extract_stdlib_imports(source):
            if imp not in seen_imports:
                seen_imports.add(imp)
                all_imports.append(imp)

        body = strip_module(source, label)
        all_bodies.append((label, body))

    # Build output
    sections: list[str] = [
        "# train_gpt.py — La Pulga (lapulga-llm)",
        "# Auto-generated by scripts/build_submission.py — DO NOT EDIT BY HAND",
        "# OpenAI Parameter-Golf submission format: single standalone file",
        "",
        "# ── Imports ─────────────────────────────────────────────────────────────",
        *all_imports,
        "",
    ]

    for label, body in all_bodies:
        if not body.strip():
            continue
        sections.append(f"# ── {label} {'─' * max(0, 70 - len(label))}─")
        sections.append("")
        sections.append(body)
        sections.append("")

    output = "\n".join(sections) + "\n"

    OUTPUT_FILE.write_text(output, encoding="utf-8")

    size_kb = OUTPUT_FILE.stat().st_size / 1024
    print(f"Built: {OUTPUT_FILE}")
    print(f"Size:  {size_kb:.1f} KB")
    print(f"Lines: {output.count(chr(10)):,}")

    # Quick syntax check
    try:
        ast.parse(output)
        print("Syntax: OK")
    except SyntaxError as e:
        print(f"Syntax: ERROR — {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    build()
